//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileRapWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int bannerAutoSEQ { get; set; }
        public string bannerTitle { get; set; }
        public string bannerDesc { get; set; }
        public string bannerLink { get; set; }
        public string bannerPath { get; set; }
    }
}
